import type { EmployeeSkillCategory } from "@/lib/scoring";

export type LessonType =
  | "CONCEPT"
  | "DEMONSTRATION"
  | "INTERACTIVE_EXERCISE"
  | "TOOL_PRACTICE"
  | "PROMPT_EXERCISE"
  | "DECISION_EXERCISE"
  | "KNOWLEDGE_CHECK"
  | "REFLECTION"
  | "WORKFLOW_PRACTICE";

export type LessonSeed = {
  title: string;
  type: LessonType;
  objective: string;
  whyItMatters: string;
  concept: string;
  example: string;
  tryItPrompt: string;
  evaluatePrompt: string;
  exercise: string;
  knowledgeCheckQuestion: string;
  knowledgeCheckOptions: string[];
  knowledgeCheckCorrectIndex: number;
  takeaway: string;
  skills: EmployeeSkillCategory[];
  durationMin: number;
};

export type CourseSeed = {
  workflowTitle: string;
  title: string;
  description: string;
  department: string;
  role: string;
  skills: EmployeeSkillCategory[];
  tools: string[];
  lessons: LessonSeed[];
};

/**
 * Single source of truth for role-based learning paths - used by the
 * initial seed script and by ensureCourseCatalog() (idempotent runtime
 * top-up, same pattern as GLOBAL_TOOL_CATALOG / SIMULATION_CATALOG) so new
 * paths reach already-provisioned organizations without a full reseed.
 * Every lesson follows Objective -> Why it matters -> Learn -> See it ->
 * Try it -> Evaluate -> Apply -> Knowledge check -> Takeaway.
 */
export const COURSE_CATALOG: CourseSeed[] = [
  {
    workflowTitle: "AI-Assisted Claims Document Processing",
    title: "Use AI to process claims documents faster",
    description: "Extract and summarize claim documents with AI, without inventing facts the file doesn't support.",
    department: "Claims",
    role: "Claims Adjusters",
    skills: ["prompting", "evaluation"],
    tools: ["ChatGPT", "Claims Portal"],
    lessons: [
      {
        title: "Why document extraction is the fastest AI win in claims",
        type: "CONCEPT",
        objective: "Explain why extracting facts from claim documents is a high-value, checkable AI use case.",
        whyItMatters: "A single auto claim file can run 40+ pages across police reports, estimates, and statements. AI can pull out the key facts in seconds, freeing you to focus on judgment calls instead of page-flipping.",
        concept: "AI can read a stack of claim documents and produce a structured summary of key facts in seconds, as long as it's asked to cite where each fact came from.",
        example: "A 40-page auto claim file becomes: 'Police report confirms other driver at fault (p.3). Two repair estimates: $6,200 and $8,000 (pp.12,18) - not reconciled. Recorded statement consistent with police report (p.22).'",
        tryItPrompt: "Paste a claim document excerpt into your approved AI tool and ask it to extract the key facts with page references for each.",
        evaluatePrompt: "An AI summary states 'the vehicle was totaled' but the actual repair estimate in the file says 'repairable, $6,200.' Is this summary trustworthy?",
        exercise: "Use AI to extract key facts from your next 3 claim files before writing your adjuster notes, and compare how much faster your file review is.",
        knowledgeCheckQuestion: "What makes an AI-extracted claim summary trustworthy?",
        knowledgeCheckOptions: [
          "It's written in confident, professional language",
          "Each fact traces back to a specific page or document in the file",
          "It's shorter than the original documents",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A claim summary is only as trustworthy as its traceability - always ask AI to cite where each fact came from, not just state it.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Flagging discrepancies instead of picking one number",
        type: "DECISION_EXERCISE",
        objective: "Recognize when a claim file has conflicting information AI should flag rather than silently resolve.",
        whyItMatters: "When two repair estimates disagree, or a statement doesn't quite match a police report, that discrepancy is often exactly what the adjuster needs to see - not something to smooth over.",
        concept: "AI should be explicitly asked to flag contradictions and gaps in a claim file, not just produce a clean-sounding summary that quietly picks one version of events.",
        example: "Instead of a summary that just states 'repair cost: $6,200,' a good prompt asks AI to flag that two estimates exist ($6,200 and $8,000) and by how much they differ.",
        tryItPrompt: "Ask AI to summarize a claim file AND explicitly flag any numbers, dates, or facts that don't match across documents.",
        evaluatePrompt: "AI's summary of a claim silently uses the higher of two conflicting repair estimates without mentioning the lower one exists. What's the risk here?",
        exercise: "On your next file with more than one estimate or statement, have AI explicitly list every discrepancy it finds before you write your notes.",
        knowledgeCheckQuestion: "Why should AI flag discrepancies instead of resolving them?",
        knowledgeCheckOptions: [
          "Because AI isn't capable of doing math",
          "Because deciding which conflicting fact to trust is the adjuster's judgment call, not AI's",
          "Because it makes the summary longer",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI should surface disagreements in a file, not quietly resolve them - resolving conflicting facts is your judgment call to make.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Underwriting Research",
    title: "Use AI to research risk without overstating what you found",
    description: "Research applicant risk profiles with AI while keeping every claim traceable to a real source.",
    department: "Underwriting",
    role: "Underwriters",
    skills: ["prompting", "evaluation"],
    tools: ["ChatGPT", "Power BI"],
    lessons: [
      {
        title: "Researching an applicant's public risk profile efficiently",
        type: "PROMPT_EXERCISE",
        objective: "Write a research prompt that produces a usable, source-cited risk profile from public information.",
        whyItMatters: "Manual research into an applicant's safety record and public footprint is one of the slowest parts of underwriting - AI can compress it dramatically if you ask it to cite sources.",
        concept: "AI can synthesize public information about a business into a usable risk profile, as long as you require it to cite where each claim came from.",
        example: "Ask: 'Research ABC Contracting's public safety record and financial stability signals, and cite the source for each finding.'",
        tryItPrompt: "Pick a real applicant from your queue and generate an AI research brief with sources cited for each finding.",
        evaluatePrompt: "AI's research brief states a company has 'no safety violations' with no source cited. Should you treat this as a confirmed clean record?",
        exercise: "Before your next pricing decision, generate an AI research brief and personally verify at least one cited source.",
        knowledgeCheckQuestion: "What should you do with a risk claim in an AI research brief that has no cited source?",
        knowledgeCheckOptions: [
          "Include it in your pricing rationale since AI found it",
          "Verify it against a real database before it factors into pricing",
          "Assume it's true because no contradicting information was found",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "'No evidence found' is not the same as 'confirmed clean' - verify anything that will affect pricing against the actual source.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Telling absence of evidence from actual evidence",
        type: "REFLECTION",
        objective: "Practice distinguishing a genuinely confirmed risk finding from an unconfirmed absence of results.",
        whyItMatters: "An AI search that finds nothing negative about an applicant isn't the same as a verified clean record - and that distinction can matter enormously once it factors into a price.",
        concept: "AI research surfaces what's publicly findable, not what's true. A clean AI search result means 'nothing turned up,' not 'nothing exists.'",
        example: "'No reported safety violations found' should be read as 'not found in this search,' not as a certified clean regulatory record.",
        tryItPrompt: "Review an AI-generated risk profile and mark which findings are confirmed facts versus absence-of-evidence claims.",
        evaluatePrompt: "Look back at your last underwriting research brief. Which claims in it were actually verified, and which were just 'nothing came up'?",
        exercise: "For your next 3 risk profiles, explicitly label each finding as 'confirmed' or 'not found in search' before it goes into your pricing notes.",
        knowledgeCheckQuestion: "What does a clean AI search result about an applicant's safety record actually tell you?",
        knowledgeCheckOptions: [
          "The applicant definitely has no safety violations",
          "Nothing negative turned up in that particular search, which isn't the same as a confirmed clean record",
          "The applicant is a low-risk client",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Label every finding as confirmed or unconfirmed - the habit costs seconds and prevents a real pricing mistake.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Policy & Claims Inquiry Response",
    title: "Respond to policyholders faster without overpromising",
    description: "Draft accurate, empathetic responses to policyholder questions and disputes with AI.",
    department: "Customer Service",
    role: "Customer Service Representatives",
    skills: ["prompting", "evaluation"],
    tools: ["Claude", "Claims Portal"],
    lessons: [
      {
        title: "Drafting responses policyholders will actually trust",
        type: "PROMPT_EXERCISE",
        objective: "Write a prompt that produces a specific, accurate response instead of a generic template.",
        whyItMatters: "A generic-sounding AI draft is a fast way to make a frustrated policyholder feel unheard - the fix is almost always in how you prompt it, not in rewriting the whole thing by hand.",
        concept: "Good AI-drafted responses reference the policyholder's actual policy terms and claim status, not a generic description of what policies 'usually' cover.",
        example: "Instead of 'we're sorry for any inconvenience,' a good draft opens with 'I understand the water damage exclusion in your policy is frustrating, especially given the timeline of your claim.'",
        tryItPrompt: "Write a prompt for AI that includes the policyholder's specific policy section and claim status, and an instruction to reference both by name.",
        evaluatePrompt: "AI drafts: 'We're sorry for any inconvenience. Your issue has been addressed.' Does this tell the policyholder what was actually decided?",
        exercise: "Draft a response using AI for a real inquiry this week, then edit it to reference the specific policy terms involved.",
        knowledgeCheckQuestion: "What's the fastest way to stop AI from producing a generic-sounding response?",
        knowledgeCheckOptions: [
          "Ask AI to sound friendlier",
          "Give the prompt the specific policy terms and claim status to reference by name",
          "Always rewrite the whole draft yourself",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Specificity in the prompt produces specificity in the draft - reference the real policy and claim, not 'your issue.'",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Never letting AI imply a coverage decision that hasn't happened",
        type: "DECISION_EXERCISE",
        objective: "Catch and correct AI drafts that state or imply a coverage outcome that hasn't actually been decided.",
        whyItMatters: "Stating that a claim 'will be covered' when no such decision was made isn't just a tone problem - it's a promise Havenbrook may not be able to keep, and it makes things worse when it's walked back.",
        concept: "AI drafts should describe only what has actually been decided or verified - never a coverage outcome, payment, or timeline that hasn't been confirmed.",
        example: "'I've issued a refund' should never appear in a draft unless a refund has actually been processed - describe what's true, not what would be nice to say.",
        tryItPrompt: "Review an AI-drafted response and mark any statement that describes an action or decision you haven't actually confirmed.",
        evaluatePrompt: "AI's draft says 'we've decided to cover your claim in full' but no such review has actually happened. What would you change before sending?",
        exercise: "Before sending your next AI-assisted response, check every sentence that states an outcome or action against what's actually confirmed in the system.",
        knowledgeCheckQuestion: "What should you do if an AI draft states an outcome that hasn't actually been decided?",
        knowledgeCheckOptions: [
          "Send it anyway since it sounds helpful",
          "Correct it to reflect only what's actually been confirmed, before sending",
          "Soften the language slightly but keep the claim",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Never let a draft describe an action or decision that hasn't actually happened - verify or correct it before it goes out.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Insurance Sales Prospecting",
    title: "Use AI to qualify and research inbound insurance leads",
    description: "Research accounts and draft personalized outreach in a fraction of the time.",
    department: "Sales",
    role: "Insurance Sales Agents",
    skills: ["prompting", "evaluation", "workflowDesign"],
    tools: ["ChatGPT", "Salesforce"],
    lessons: [
      {
        title: "Researching a commercial prospect in minutes, not hours",
        type: "PROMPT_EXERCISE",
        objective: "Write a research prompt that produces a usable, source-cited account brief from public information only.",
        whyItMatters: "Manual account research is one of the biggest time sinks before a first call - AI can compress it dramatically if you ask it the right way.",
        concept: "AI can synthesize public information about a business into a usable account brief for insurance prospecting.",
        example: "Ask: 'Research Riverside Logistics and summarize their business, size, and any recent news relevant to a commercial insurance conversation.'",
        tryItPrompt: "Pick a real lead from your pipeline and generate an AI research brief on it, with sources cited.",
        evaluatePrompt: "AI's research brief states a specific employee count for a prospect with no source cited. Should you include that figure in your outreach as-is?",
        exercise: "Before your next call, generate an AI research brief for that account and use it to shape your first two questions.",
        knowledgeCheckQuestion: "What should you do with a specific fact (like an employee count) that AI includes in a research brief?",
        knowledgeCheckOptions: [
          "Use it directly in outreach since AI found it",
          "Verify it against a real source before referencing it to a prospect",
          "Remove all numbers from AI research briefs on principle",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI research is a starting hypothesis, not a verified fact - confirm specific claims before they reach a prospect.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Personalizing outreach without starting from scratch",
        type: "TOOL_PRACTICE",
        objective: "Turn an account research brief into a personalized outreach draft using AI inside your actual workflow.",
        whyItMatters: "The best-performing outreach references something specific about the prospect's business - AI can generate that personalization fast, but only from real research you feed it.",
        concept: "The best AI-drafted outreach references something specific about the prospect's business or risk profile, not a generic pitch.",
        example: "Reference a recent expansion or a specific coverage gap in the opening line, not 'I hope this finds you well.'",
        tryItPrompt: "Draft a personalized outreach email using your AI research brief from the previous lesson.",
        evaluatePrompt: "AI's outreach draft opens with 'I hope this email finds you well' despite having real research available about the prospect's recent expansion. Is this a good use of the research?",
        exercise: "Send your next piece of AI-assisted outreach only after confirming it references something specific and verified about the prospect.",
        knowledgeCheckQuestion: "What separates a strong AI-drafted outreach email from a generic one?",
        knowledgeCheckOptions: [
          "It's longer",
          "It references something specific and real about the prospect",
          "It avoids mentioning insurance products",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Personalization comes from specificity, not length - one real, relevant detail beats three generic value props.",
        skills: ["prompting"],
        durationMin: 8,
      },
    ],
  },
  {
    workflowTitle: "AI-Generated Campaign Briefs & Copy Drafts",
    title: "Turn one brief into every channel's copy",
    description: "Draft campaign briefs and channel-specific copy variants with AI, keeping compliance in view.",
    department: "Marketing",
    role: "Marketers",
    skills: ["prompting"],
    tools: ["Claude", "Microsoft 365"],
    lessons: [
      {
        title: "From goal to structured brief in one prompt",
        type: "PROMPT_EXERCISE",
        objective: "Turn a one-line campaign goal into a structured brief by supplying AI with real constraints.",
        whyItMatters: "A brief built on assumptions AI invented (generic audience, made-up budget) has to be redone from scratch - supplying real constraints upfront saves that rework.",
        concept: "AI can expand a one-line campaign goal into a structured brief with audience, message, and channels.",
        example: "Input: 'Drive awareness for our small-business bundle before renewal season.' Output: a structured brief with audience, key message, and channel plan.",
        tryItPrompt: "Turn one of your current campaign goals into a structured brief using AI, explicitly supplying your real audience and budget range in the prompt.",
        evaluatePrompt: "AI's brief recommends a $75,000 budget 'based on typical renewal campaigns.' Your team's actual quarterly marketing budget is $30,000. Should this figure stay in the brief?",
        exercise: "Turn one of your current campaign goals into a structured brief using AI.",
        knowledgeCheckQuestion: "What's the risk of giving AI only a one-line goal with no other context?",
        knowledgeCheckOptions: [
          "AI will refuse to answer",
          "AI will invent plausible-sounding audience and budget details that may not match reality",
          "The brief will be too short to use",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A brief is only as grounded as the constraints you supply - a bare goal produces a plausible-sounding brief built on invented specifics.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Keeping coverage language compliant",
        type: "DECISION_EXERCISE",
        objective: "Recognize AI-drafted marketing language that creates regulatory risk before it ships.",
        whyItMatters: "Insurance marketing copy has real regulatory guardrails - a word like 'guaranteed' that reads as harmless in most industries can be a genuine compliance issue here.",
        concept: "Any AI-drafted copy that describes coverage, pricing, or guarantees needs a compliance check before it ships - AI doesn't know Havenbrook's regulatory guardrails by default.",
        example: "'Complete protection, guaranteed' sounds like normal marketing copy but implies a coverage promise that policy terms and exclusions may not support.",
        tryItPrompt: "Review an AI-drafted piece of campaign copy and flag any word or phrase that implies a coverage guarantee or promise.",
        evaluatePrompt: "AI's campaign copy draft includes the phrase 'complete protection, guaranteed.' What would you do with this phrase before it ships?",
        exercise: "Before your next campaign ships, personally scan the AI-drafted copy for guarantee-style language and route it to compliance if you find any.",
        knowledgeCheckQuestion: "Why does 'guaranteed' need extra scrutiny in insurance marketing copy specifically?",
        knowledgeCheckOptions: [
          "It's considered old-fashioned marketing language",
          "It implies a coverage promise that the policy's actual terms and exclusions may not support",
          "It's too vague to be effective",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI doesn't know Havenbrook's compliance guardrails by default - treat any coverage or guarantee language in a draft as a required compliance check.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Financial Reporting Narratives",
    title: "Draft financial commentary leadership will trust",
    description: "Turn loss-ratio and budget variance data into a clear, accurate narrative with AI.",
    department: "Finance",
    role: "Financial Analysts",
    skills: ["evaluation"],
    tools: ["ChatGPT", "Power BI"],
    lessons: [
      {
        title: "Why variance data needs a narrative",
        type: "CONCEPT",
        objective: "Explain why raw loss-ratio numbers need a written explanation before they reach leadership.",
        whyItMatters: "A number without context ('+9 points loss ratio') tells a stakeholder almost nothing about whether it's a problem - the narrative is what makes the report useful.",
        concept: "Numbers alone don't tell stakeholders why something changed - AI can draft the 'why' from the data, once the actual cause is confirmed.",
        example: "Instead of just '+9pts loss ratio,' a narrative reads: 'The commercial auto loss ratio rose 9 points, driven by a cluster of large weather-related claims confirmed by the claims team.'",
        tryItPrompt: "Feed a loss-ratio variance table into AI and ask it to draft commentary explaining the change.",
        evaluatePrompt: "AI's variance narrative states a cause with confident language ('due to') but you haven't actually confirmed that cause with claims yet. Is that language appropriate?",
        exercise: "Feed a loss-ratio variance table into AI and ask it to draft commentary explaining the change.",
        knowledgeCheckQuestion: "What makes a variance narrative more useful than the raw numbers alone?",
        knowledgeCheckOptions: [
          "It's shorter",
          "It explains why the number changed, in plain language",
          "It removes numbers a reader might question",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "The value of a narrative is the 'why' - but only state a cause with confidence once it's actually confirmed, not just inferred from the number.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Distinguishing frequency from severity before you explain it",
        type: "DECISION_EXERCISE",
        objective: "Recognize when an AI-drafted explanation conflates claim frequency and severity without checking which one actually happened.",
        whyItMatters: "A loss ratio can rise because more claims happened, or because a few claims got much more expensive - the two call for completely different business responses.",
        concept: "Before accepting an AI-drafted explanation for a loss-ratio change, confirm with claims or underwriting whether the driver was frequency, severity, or both.",
        example: "'Rising claim frequency' and 'a handful of large claims' produce the same loss-ratio number but suggest very different fixes.",
        tryItPrompt: "Look at an AI-drafted variance explanation and identify whether it distinguishes frequency from severity, or just describes 'more losses.'",
        evaluatePrompt: "AI's memo recommends 'rate action across the full line' based on an unconfirmed frequency increase. What would you check before this recommendation goes to leadership?",
        exercise: "Before finalizing your next variance memo, explicitly confirm with claims whether the driver was frequency, severity, or a specific cluster of claims.",
        knowledgeCheckQuestion: "Why does it matter whether a loss-ratio increase came from frequency or severity?",
        knowledgeCheckOptions: [
          "It doesn't - the loss ratio number is what matters",
          "They call for different business responses, so recommending action requires knowing which one happened",
          "Frequency is always worse than severity",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Never let a business recommendation ride along with an unconfirmed cause - frequency and severity need different responses.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
  {
    workflowTitle: "Internal Knowledge Management Assistant",
    title: "Use AI to answer internal procedure questions accurately",
    description: "Help colleagues find the current, correct internal procedure using AI grounded in real SOPs.",
    department: "Operations",
    role: "Operations Coordinators",
    skills: ["evaluation", "automation"],
    tools: ["Claude", "Microsoft 365"],
    lessons: [
      {
        title: "Grounding AI answers in the actual SOP, not general knowledge",
        type: "CONCEPT",
        objective: "Explain why an internal procedure question needs to be answered from Havenbrook's actual documents, not AI's general training.",
        whyItMatters: "AI's general knowledge about 'how insurance companies usually handle X' can sound authoritative and still be completely wrong for Havenbrook's actual documented policy.",
        concept: "For any compliance-sensitive procedure question, AI should search and cite Havenbrook's actual internal SOP documents, not answer from general knowledge about the industry.",
        example: "'Per SOP section 4.2, after three unsuccessful contact attempts...' is groundable and checkable. 'Insurance companies typically wait 30 days...' is not - it's a generic industry pattern, not Havenbrook's policy.",
        tryItPrompt: "Ask AI a procedure question using only your internal SOP documents as its source material, and require a section citation.",
        evaluatePrompt: "AI answers a procedure question confidently without citing any internal document. Should you pass this answer along as Havenbrook's policy?",
        exercise: "The next time a colleague asks you a procedure question you're not fully sure of, use AI to search the actual SOPs rather than answering from memory.",
        knowledgeCheckQuestion: "Why is a generic 'insurance companies typically...' answer risky for an internal procedure question?",
        knowledgeCheckOptions: [
          "It's usually factually wrong",
          "It may not reflect Havenbrook's actual documented policy, even if it sounds plausible",
          "It takes longer to generate",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A plausible-sounding industry answer is not the same as Havenbrook's actual policy - always ground procedure answers in the real SOP.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Checking that a cited SOP section is still current",
        type: "DECISION_EXERCISE",
        objective: "Catch cases where AI cites a real but outdated SOP section.",
        whyItMatters: "A citation makes an answer look trustworthy, but if the cited section was superseded by a policy update, following it creates a real process error.",
        concept: "A cited SOP section should be checked against the current version before you pass the answer along - citations reduce guessing, but don't guarantee currency.",
        example: "AI cites 'section 4.2' correctly, but that section was updated two revisions ago and the current procedure is different.",
        tryItPrompt: "Take an AI-cited SOP answer and check the document's version/revision date before trusting it as current.",
        evaluatePrompt: "AI cites a specific, real SOP section for a procedure question, but you're not sure if it's the latest version. What do you do before answering your colleague?",
        exercise: "For your next 3 AI-assisted procedure answers, confirm the cited section's revision date before passing the answer along.",
        knowledgeCheckQuestion: "What should you check after AI cites a specific SOP section?",
        knowledgeCheckOptions: [
          "Nothing - a citation means it's correct",
          "Whether that section is still the current version, not a superseded one",
          "Whether the section number is a round number",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A citation tells you where an answer came from, not whether it's still current - check the revision date before you rely on it.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Job Descriptions & Resume Screening",
    title: "Hire faster without losing the human review",
    description: "Draft job descriptions and pre-screen resumes with AI.",
    department: "HR",
    role: "Recruiters",
    skills: ["evaluation"],
    tools: ["ChatGPT", "Microsoft 365"],
    lessons: [
      {
        title: "Writing a job description in minutes, not hours",
        type: "PROMPT_EXERCISE",
        objective: "Draft a strong first-pass job description from role, level, and must-have skills.",
        whyItMatters: "A blank page is the slowest part of writing a JD - giving AI the 2-3 facts only you know turns that blank page into a first draft in minutes.",
        concept: "AI can draft a strong first version from just the role, level, and key requirements.",
        example: "Input the role title (Claims Adjuster) and 3 must-have skills; AI drafts the full JD including responsibilities and qualifications.",
        tryItPrompt: "Draft a JD for an open role using AI, then edit it for Havenbrook's voice.",
        evaluatePrompt: "AI's draft JD lists '10+ years experience' for a role you specified as entry-level. Should you keep this requirement?",
        exercise: "Draft a JD for an open role using AI, then edit it for Havenbrook's voice.",
        knowledgeCheckQuestion: "What's the fastest way to get a strong first-draft JD from AI?",
        knowledgeCheckOptions: [
          "Ask for 'a job description' with no other detail",
          "Give AI the role, level, and 2-3 must-have skills",
          "Write the whole thing yourself first, then ask AI to polish it",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A few real, specific inputs (role, level, must-haves) produce a far more useful draft than a vague one-word request.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Using AI screening without introducing bias",
        type: "DECISION_EXERCISE",
        objective: "Recognize when AI's screening criteria have drifted from the role's actual written requirements.",
        whyItMatters: "AI screening can process resumes far faster than a manual read, but if its criteria drift toward proxies like which specific carrier someone worked at, you inherit a bias problem you'll have to answer for later.",
        concept: "AI screening should score against explicit role criteria - always spot-check for bias before trusting the shortlist.",
        example: "Review a sample of AI-screened-out resumes each month to check the criteria are working as intended.",
        tryItPrompt: "List the explicit criteria you'd want AI to screen for in your next open claims or underwriting role.",
        evaluatePrompt: "AI explains a candidate was ranked lower partly because they worked at a smaller regional carrier rather than a national one. Is this an appropriate screening criterion?",
        exercise: "For your next screening pass, write down your criteria before running any resumes through AI, and spot-check 5 resumes it screened out.",
        knowledgeCheckQuestion: "What should trigger a human override of an AI screening decision?",
        knowledgeCheckOptions: [
          "The candidate has an unusual resume format",
          "AI's stated reasoning references something not on your written job requirements",
          "The candidate applied outside business hours",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Any AI-stated screening reason that isn't one of your written requirements is a signal to override, not a tiebreaker to accept.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Regulatory Compliance Review",
    title: "Use AI for a compliance first pass, not the final call",
    description: "Speed up regulatory review of marketing and communications with AI while keeping the final decision human.",
    department: "Compliance",
    role: "Compliance Analysts",
    skills: ["evaluation"],
    tools: ["ChatGPT"],
    lessons: [
      {
        title: "What AI can flag vs. what only a compliance officer can decide",
        type: "CONCEPT",
        objective: "Draw a clear line between flagging potential issues (AI can do this) and clearing copy for release (only a compliance officer should).",
        whyItMatters: "The efficiency gain from AI-assisted compliance review only holds up if the division of labor is right - AI flagging risky language fast is a real win; AI deciding copy is compliant is a real risk.",
        concept: "AI can compare marketing and communications copy against a compliance checklist and flag potentially risky language quickly and consistently. Whether flagged language is actually acceptable is a judgment call for a licensed compliance officer.",
        example: "AI flagging 'this phrase uses guarantee-style language' is useful. AI stating 'this phrase is acceptable and needs no disclosure' oversteps into a compliance decision.",
        tryItPrompt: "Think of the last piece of copy you reviewed - which parts were mechanical checklist comparison, and which required an actual compliance judgment call?",
        evaluatePrompt: "AI's compliance review both flags a phrase and states it's acceptable without disclosure. Which part of that output would you keep, and which would you discard?",
        exercise: "On your next compliance review, use AI only to build the list of potentially risky phrases - write your own clearance recommendation separately.",
        knowledgeCheckQuestion: "What is AI well-suited to do in a compliance review?",
        knowledgeCheckOptions: [
          "Deciding whether a guarantee-style phrase is acceptable for release",
          "Comparing copy against a compliance checklist to flag potentially risky language",
          "Signing off on final campaign copy",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Let AI build the list of what might be risky; keep the judgment about whether it's actually acceptable with a licensed compliance officer.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Checking state-specific requirements, not just general guidelines",
        type: "TOOL_PRACTICE",
        objective: "Use AI to check copy against state-specific regulatory requirements rather than general best practices.",
        whyItMatters: "A multi-state campaign launch means different disclosure requirements apply in different states - a general compliance check can clear copy that's actually non-compliant in one or two specific states.",
        concept: "AI review should be run against the specific state guidelines that apply to a launch, not general insurance marketing best practices.",
        example: "Copy cleared against 'general best practices' might still violate a specific disclosure requirement that only applies in two of eight launch states.",
        tryItPrompt: "Feed AI your state-specific compliance guidelines (not general best practices) and ask it to check a piece of copy against each relevant state.",
        evaluatePrompt: "AI's review says copy is compliant based on general insurance marketing guidelines, without checking any specific state's requirements. What's missing?",
        exercise: "On your next multi-state review, explicitly list which states the campaign is launching in and check the copy against each state's specific requirements.",
        knowledgeCheckQuestion: "Why is a 'general best practices' compliance check insufficient for a multi-state campaign?",
        knowledgeCheckOptions: [
          "General best practices are always wrong",
          "Insurance regulations vary by state, so a general check can miss a state-specific requirement",
          "It takes too long to run a general check",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Always check against the specific states a campaign is launching in - general best practices aren't a substitute for state-specific regulatory requirements.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "Contract & Policy Language Review",
    title: "Speed up contract review without skipping legal judgment",
    description: "Use AI for a first-pass playbook comparison while keeping real risk decisions with an attorney.",
    department: "Legal",
    role: "Contracts Counsel",
    skills: ["evaluation"],
    tools: ["ChatGPT"],
    lessons: [
      {
        title: "What AI can flag vs. what only an attorney can decide",
        type: "CONCEPT",
        objective: "Draw a clear line between clause-comparison (AI can do this) and risk acceptance (only an attorney should).",
        whyItMatters: "The efficiency gain from AI contract review only holds up if the division of labor is right - AI finding deviations fast is a real win; AI deciding whether a deviation is acceptable is a real risk, especially for vendors handling claims data.",
        concept: "AI can compare contract language against a standard playbook and flag deviations quickly and consistently. Whether a flagged deviation is acceptable risk is a judgment call for a licensed attorney.",
        example: "AI flagging 'the data retention clause was changed' is useful. AI recommending 'accept this change, it's reasonable' oversteps into legal judgment.",
        tryItPrompt: "Think of the last contract you reviewed - which parts were mechanical comparison, and which required your own judgment call?",
        evaluatePrompt: "AI's contract review output both flags a changed clause and recommends accepting it. Which part of that output would you keep, and which would you discard?",
        exercise: "On your next contract review, use AI only to build the list of what changed - write your own acceptance recommendation separately.",
        knowledgeCheckQuestion: "What is AI well-suited to do in contract review?",
        knowledgeCheckOptions: [
          "Deciding whether a liability cap is acceptable for this vendor",
          "Comparing clause language against a standard playbook to flag deviations",
          "Signing off on the final redline",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Let AI build the list of what changed; keep the judgment about whether a change is acceptable with a licensed attorney.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Comparing a redline against your standard playbook",
        type: "TOOL_PRACTICE",
        objective: "Use AI to produce a clause-by-clause comparison of a redlined contract against your standard terms.",
        whyItMatters: "A thorough manual comparison of a long redlined contract is slow and easy to skim past a subtle change, especially in data-handling terms that matter for claims data vendors.",
        concept: "AI flags non-standard or high-risk clauses against Havenbrook's playbook before legal review.",
        example: "AI identifies that Section 6's liability cap changed from mutual to vendor-only, and Section 9's data handling terms were broadened.",
        tryItPrompt: "Feed AI your standard terms and a redlined contract, and ask it to list every clause that deviates.",
        evaluatePrompt: "AI's comparison lists 5 flagged clauses. On manual review, you find a 6th change AI didn't catch, in a footnote. What does this tell you about relying on AI comparison alone?",
        exercise: "On your next contract, run the AI comparison first, then do one manual pass focused specifically on footnotes and appendices.",
        knowledgeCheckQuestion: "Why should an AI-assisted clause comparison still be followed by a targeted manual pass?",
        knowledgeCheckOptions: [
          "AI comparisons are never useful",
          "AI may miss changes in unusual locations like footnotes or appendices",
          "It's required by the tool's license",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI comparison is a strong first pass, not a guaranteed complete one - a short targeted manual check covers its blind spots.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Board Reporting",
    title: "Turn department updates into a board-ready narrative",
    description: "Synthesize scattered updates into an accurate board memo with AI.",
    department: "Executive",
    role: "Executives",
    skills: ["evaluation", "automation"],
    tools: ["Claude", "Microsoft 365"],
    lessons: [
      {
        title: "Synthesizing scattered updates without losing accuracy",
        type: "PROMPT_EXERCISE",
        objective: "Turn several inconsistent department updates into one coherent draft narrative using AI.",
        whyItMatters: "Reconciling five different department leads' updates manually eats the time you need to actually verify the numbers - AI can do the reconciliation so you can spend your time checking, not assembling.",
        concept: "AI drafts a first-pass board narrative from department metrics; executives edit and finalize.",
        example: "Five department updates and a rough spreadsheet become one structured one-page summary organized by department.",
        tryItPrompt: "Feed AI your team's raw updates (not your own summary of them) and ask for a one-page synthesis organized by department.",
        evaluatePrompt: "AI's synthesized narrative states 'loss ratio improved 3 points quarter-over-quarter' by comparing two updates that actually covered different time periods. What's the risk in this figure?",
        exercise: "For your next board update, feed AI the raw source updates and compare its draft against each source line by line.",
        knowledgeCheckQuestion: "What's the best raw material to give AI when synthesizing multiple department updates?",
        knowledgeCheckOptions: [
          "Your own condensed summary of the updates",
          "The original, unsummarized updates from each department",
          "Just the numbers, with no context",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Synthesizing from the original sources preserves the detail needed to catch a mismatch - synthesizing from your own summary compounds whatever you already left out.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Verifying every number before it reaches the board",
        type: "DECISION_EXERCISE",
        objective: "Decide which figures in an AI-drafted board memo need verification before the memo is final.",
        whyItMatters: "A board memo is read and acted on by people who won't check your math - an unverified figure that turns out wrong costs credibility in a way few other documents do.",
        concept: "Any figure that will appear in a board-facing document must be verified against its source system before the memo is finalized.",
        example: "An 'estimated 300 hours saved' figure that doesn't trace back to any specific source number shouldn't go into the memo unchanged.",
        tryItPrompt: "Take an AI-drafted memo and trace every number back to a specific source line before treating it as final.",
        evaluatePrompt: "The memo is due in 10 minutes and one figure's source is ambiguous. Do you include it as-is, remove it, or flag it as an estimate?",
        exercise: "Before your next board memo goes out, personally trace each figure back to its source and note anywhere you couldn't.",
        knowledgeCheckQuestion: "What should you do with a figure in a board memo whose source you can't verify in time?",
        knowledgeCheckOptions: [
          "Include it as stated since it sounds reasonable",
          "Remove it or clearly label it as an estimate rather than a confirmed figure",
          "Round it to a cleaner number",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "An honestly-labeled estimate is far better than a confident-sounding number you can't actually trace back to its source.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
  {
    workflowTitle: "AI Code Review Assistant",
    title: "Use AI code review without skipping design thinking",
    description: "Get a fast AI first-pass review on Claims Portal changes while keeping human review focused on what actually needs it.",
    department: "IT",
    role: "Software Engineers",
    skills: ["automation", "evaluation"],
    tools: ["ChatGPT"],
    lessons: [
      {
        title: "What AI catches well in a diff, and what it misses",
        type: "CONCEPT",
        objective: "Distinguish between review tasks AI handles well (style, common bugs, missing tests) and ones it doesn't (architecture, intent).",
        whyItMatters: "Knowing AI's real strengths and blind spots in code review lets you actually save reviewer time on Claims Portal changes instead of just adding an extra pass that catches the same things a human would.",
        concept: "AI reviews the diff first for bugs, style, and missing tests, then a human reviewer focuses on design.",
        example: "AI reliably catches an unhandled null case or a missing test for a new branch; it's much weaker at judging whether a change to the Claims Portal's data model is the right long-term approach.",
        tryItPrompt: "Look at your last AI-reviewed pull request and separate its comments into 'mechanical' (style, bugs, tests) versus 'design' (architecture, approach).",
        evaluatePrompt: "AI's review comment says 'this function could be refactored for better architecture' with no further detail. Is this the kind of feedback AI is well-suited to give?",
        exercise: "On your next PR touching the Claims Portal, ask AI to review first, then spend your own review time only on the design-level questions it can't meaningfully answer.",
        knowledgeCheckQuestion: "Which task is AI generally weaker at in code review?",
        knowledgeCheckOptions: [
          "Flagging an unhandled null case",
          "Judging whether an architectural approach fits the Claims Portal's long-term direction",
          "Noticing a missing test for a new code path",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI is strong on the mechanical review; a human reviewer's time is best spent on the design judgment AI can't make.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Focusing human review on design, not syntax",
        type: "DECISION_EXERCISE",
        objective: "Decide when to defer to AI's mechanical review versus when a change needs deeper human design review.",
        whyItMatters: "If human reviewers keep re-checking what AI already covered, the workflow adds time instead of saving it, especially risky for a system claims adjusters depend on daily.",
        concept: "A human reviewer focuses on architecture and design decisions once AI has covered the mechanical pass.",
        example: "If AI's review found no bugs or style issues, a human reviewer can skip re-checking syntax and go straight to 'does this approach make sense for the Claims Portal?'",
        tryItPrompt: "For your next review, decide upfront which specific design question you'll focus on, assuming AI has the mechanical pass covered.",
        evaluatePrompt: "A reviewer spends 20 minutes re-checking style issues that AI's review already flagged and the author already fixed. Was this a good use of review time?",
        exercise: "Track your next 5 PR reviews: note how much time went to mechanical re-checking versus genuine design discussion.",
        knowledgeCheckQuestion: "What's the sign that the AI-plus-human review workflow is working well?",
        knowledgeCheckOptions: [
          "The human reviewer re-checks everything AI already covered",
          "The human reviewer spends their time on design questions AI didn't address",
          "PRs take longer to merge than before",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "The workflow pays off when human review time shifts entirely to design judgment, not when it duplicates AI's mechanical pass.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
];
