import type { EmployeeSkillCategory } from "@/lib/scoring";

export type LessonType =
  | "CONCEPT"
  | "DEMONSTRATION"
  | "INTERACTIVE_EXERCISE"
  | "TOOL_PRACTICE"
  | "PROMPT_EXERCISE"
  | "DECISION_EXERCISE"
  | "KNOWLEDGE_CHECK"
  | "REFLECTION"
  | "WORKFLOW_PRACTICE";

export type LessonSeed = {
  title: string;
  type: LessonType;
  objective: string;
  whyItMatters: string;
  concept: string;
  example: string;
  tryItPrompt: string;
  evaluatePrompt: string;
  exercise: string;
  knowledgeCheckQuestion: string;
  knowledgeCheckOptions: string[];
  knowledgeCheckCorrectIndex: number;
  takeaway: string;
  skills: EmployeeSkillCategory[];
  durationMin: number;
};

export type CourseSeed = {
  workflowTitle: string;
  title: string;
  description: string;
  department: string;
  role: string;
  skills: EmployeeSkillCategory[];
  tools: string[];
  lessons: LessonSeed[];
};

/**
 * Single source of truth for role-based learning paths - used by the
 * initial seed script and by ensureCourseCatalog() (idempotent runtime
 * top-up, same pattern as GLOBAL_TOOL_CATALOG / SIMULATION_CATALOG) so new
 * paths reach already-provisioned organizations without a full reseed.
 * Every lesson follows Objective -> Why it matters -> Learn -> See it ->
 * Try it -> Evaluate -> Apply -> Knowledge check -> Takeaway.
 */
export const COURSE_CATALOG: CourseSeed[] = [
  {
    workflowTitle: "AI Conversation Summarization & Response Drafting",
    title: "Use AI to resolve support tickets faster",
    description: "Summarize conversations, draft responses, and catch escalation risk with AI.",
    department: "Customer Support",
    role: "Support Agents",
    skills: ["prompting", "evaluation"],
    tools: ["Claude", "Zendesk"],
    lessons: [
      {
        title: "Why summarization is the fastest AI win in support",
        type: "CONCEPT",
        objective: "Explain why conversation summarization is the highest-value, lowest-risk AI use case in support.",
        whyItMatters: "You spend real time every day writing up what already happened in a ticket. AI can read the transcript and produce that summary in seconds, freeing you to focus on the resolution itself.",
        concept: "AI can read a full conversation and produce a structured summary in seconds, freeing agents to focus on resolution instead of documentation.",
        example: "A 12-message conversation about a billing dispute becomes: 'Customer disputes a duplicate charge from March. Refund issued. Customer satisfied.'",
        tryItPrompt: "Paste a recent conversation transcript into your AI tool and ask it to summarize the issue, resolution, and customer sentiment in 3 sentences.",
        evaluatePrompt: "An AI summary reads: 'Customer was happy with the resolution.' The actual transcript shows the customer wrote 'fine, I guess' after three follow-ups. Is this summary accurate?",
        exercise: "Use AI to summarize your next 3 resolved tickets before closing them, and compare how much faster your documentation is.",
        knowledgeCheckQuestion: "Why is summarization considered a low-risk AI use case in support?",
        knowledgeCheckOptions: [
          "It doesn't require reviewing the transcript at all",
          "It condenses information that's already in the transcript rather than generating new claims",
          "Customers never see the summary",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Summarization is low-risk because it condenses what's already true in the transcript — it only becomes risky if you let AI infer sentiment or outcomes the transcript doesn't actually support.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Drafting responses your customers will actually like",
        type: "PROMPT_EXERCISE",
        objective: "Write a prompt that produces a specific, on-brand response instead of a generic template.",
        whyItMatters: "A generic-sounding AI draft is a fast way to make a customer feel unheard — the fix is almost always in how you prompt it, not in rewriting the whole thing by hand.",
        concept: "Good AI-drafted responses match your brand voice and confirm the specific resolution — not a generic template.",
        example: "Instead of 'Thank you for contacting us,' a good draft opens with 'Thanks for your patience while we looked into the duplicate charge on your March invoice.'",
        tryItPrompt: "Write a prompt for AI that includes the specific issue, the specific resolution, and an instruction to reference both by name rather than generically.",
        evaluatePrompt: "AI drafts: 'We're sorry for any inconvenience. Your issue has been resolved.' Does this response tell the customer what was actually resolved?",
        exercise: "Draft a follow-up email using AI for a ticket you resolved this week, then edit it to match your voice.",
        knowledgeCheckQuestion: "What's the fastest way to stop AI from producing a generic-sounding response?",
        knowledgeCheckOptions: [
          "Ask AI to sound friendlier",
          "Give the prompt the specific issue and resolution to reference by name",
          "Always rewrite the whole draft yourself",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Specificity in the prompt produces specificity in the draft — a vague prompt about 'the issue' will always produce a vague response about 'the issue.'",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Catching escalation risk before it becomes a complaint",
        type: "DECISION_EXERCISE",
        objective: "Decide when a signal AI flags as escalation risk actually warrants proactive outreach.",
        whyItMatters: "AI can flag patterns across tickets faster than you can track them manually, but deciding what to do about a flagged pattern is still your judgment call.",
        concept: "AI can flag sentiment and repeated-contact patterns that predict escalation, so you can intervene early.",
        example: "A customer who has contacted support 3 times about the same issue in a week is a high escalation risk even if their tone stays polite.",
        tryItPrompt: "Review 5 recent tickets and note which signals (tone, repeat contact, ticket age) you'd want AI to flag.",
        evaluatePrompt: "AI flags a customer as 'high escalation risk' because they used the word 'frustrated' once in a 10-message thread that otherwise ended positively. Do you agree with the flag?",
        exercise: "For the next flagged ticket in your queue, decide within 2 minutes whether it needs proactive outreach or can wait — and note which signal drove your decision.",
        knowledgeCheckQuestion: "Which signal is the strongest predictor of escalation risk on its own?",
        knowledgeCheckOptions: [
          "A single negative word anywhere in the thread",
          "Repeated contact about the same unresolved issue",
          "The length of the conversation",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Repeat, unresolved contact is a stronger escalation signal than tone alone — a single frustrated word in an otherwise-resolved thread usually isn't worth an alarm.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Sales Prospecting",
    title: "Use AI to qualify and research your inbound leads",
    description: "Research accounts and draft personalized outreach in a fraction of the time.",
    department: "Sales",
    role: "Account Executives",
    skills: ["prompting", "evaluation", "workflowDesign"],
    tools: ["ChatGPT", "Salesforce"],
    lessons: [
      {
        title: "Researching an account in 2 minutes instead of 20",
        type: "PROMPT_EXERCISE",
        objective: "Write a research prompt that produces a usable account brief from public information only.",
        whyItMatters: "Manual account research is one of the biggest time sinks before a first call — AI can compress it dramatically if you ask it the right way.",
        concept: "AI can synthesize public information about a company into a usable account brief.",
        example: "Ask: 'Research Acme Corp and summarize their business, size, and any recent news relevant to a sales conversation.'",
        tryItPrompt: "Pick a real lead from your pipeline and generate an AI research brief on it.",
        evaluatePrompt: "AI's research brief states a specific funding amount for a prospect with no source cited. Should you include that figure in your outreach as-is?",
        exercise: "Before your next call, generate an AI research brief for that account and use it to shape your first two questions.",
        knowledgeCheckQuestion: "What should you do with a specific fact (like a funding amount) that AI includes in a research brief?",
        knowledgeCheckOptions: [
          "Use it directly in outreach since AI found it",
          "Verify it against a real source before referencing it to a prospect",
          "Remove all numbers from AI research briefs on principle",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI research is a starting hypothesis, not a verified fact — confirm specific claims before they reach a prospect.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Personalizing outreach without starting from scratch",
        type: "TOOL_PRACTICE",
        objective: "Turn an account research brief into a personalized outreach draft using AI inside your actual workflow.",
        whyItMatters: "The best-performing outreach references something specific about the prospect — AI can generate that personalization fast, but only from real research you feed it.",
        concept: "The best AI-drafted outreach references something specific about the prospect, not generic value props.",
        example: "Reference a recent funding round or product launch in the opening line, not 'I hope this finds you well.'",
        tryItPrompt: "Draft a personalized outreach email using your AI research brief from the previous lesson.",
        evaluatePrompt: "AI's outreach draft opens with 'I hope this email finds you well' despite having real research available about the company's recent product launch. Is this a good use of the research?",
        exercise: "Send your next piece of AI-assisted outreach only after confirming it references something specific and verified about the prospect.",
        knowledgeCheckQuestion: "What separates a strong AI-drafted outreach email from a generic one?",
        knowledgeCheckOptions: [
          "It's longer",
          "It references something specific and real about the prospect",
          "It avoids mentioning the product being sold",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Personalization comes from specificity, not length — one real, relevant detail beats three generic value props.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Knowing when to trust the draft vs. rewrite it",
        type: "REFLECTION",
        objective: "Practice reviewing your own AI-assisted outreach for claims you haven't personally verified.",
        whyItMatters: "The habit of checking your own AI output before sending is what separates AI-assisted selling from AI-generated mistakes reaching a prospect.",
        concept: "AI drafts are a starting point — verify facts and adjust tone before sending.",
        example: "If AI states a fact about the company you can't verify, either confirm it or remove it before sending.",
        tryItPrompt: "Review an AI-drafted email and mark any claims you'd need to verify before sending.",
        evaluatePrompt: "Look back at the last AI-drafted email you sent (or the one from this lesson). What, if anything, did you verify before sending it?",
        exercise: "For your next 3 AI-drafted emails, keep a running note of anything you had to correct — look for a pattern in what AI tends to get wrong.",
        knowledgeCheckQuestion: "What's the best habit for reviewing an AI-drafted outreach email before sending?",
        knowledgeCheckOptions: [
          "Skim for tone only",
          "Check every specific factual claim against a source you trust",
          "Trust it fully if it sounds professional",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Tone is easy to judge by ear; facts require an actual check — don't let a polished tone substitute for verifying the substance.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Generated Campaign Briefs & Copy Drafts",
    title: "Turn one brief into every channel's copy",
    description: "Draft campaign briefs and channel-specific copy variants with AI.",
    department: "Marketing",
    role: "Marketers",
    skills: ["prompting"],
    tools: ["Claude", "HubSpot"],
    lessons: [
      {
        title: "From goal to structured brief in one prompt",
        type: "PROMPT_EXERCISE",
        objective: "Turn a one-line campaign goal into a structured brief by supplying AI with real constraints.",
        whyItMatters: "A brief built on assumptions AI invented (generic audience, made-up budget) has to be redone from scratch — supplying real constraints upfront saves that rework.",
        concept: "AI can expand a one-line campaign goal into a structured brief with audience, message, and channels.",
        example: "Input: 'Drive trial signups for our new product among small business owners.' Output: a structured brief with audience, key message, and channel plan.",
        tryItPrompt: "Turn one of your current campaign goals into a structured brief using AI, explicitly supplying your real audience and budget range in the prompt.",
        evaluatePrompt: "AI's brief recommends a $50,000 budget 'based on typical holiday campaigns.' Your team's actual quarterly marketing budget is $20,000. Should this figure stay in the brief?",
        exercise: "Turn one of your current campaign goals into a structured brief using AI.",
        knowledgeCheckQuestion: "What's the risk of giving AI only a one-line goal with no other context?",
        knowledgeCheckOptions: [
          "AI will refuse to answer",
          "AI will invent plausible-sounding audience and budget details that may not match reality",
          "The brief will be too short to use",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A brief is only as grounded as the constraints you supply — a bare goal produces a plausible-sounding brief built on invented specifics.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Getting channel-specific copy that doesn't sound the same everywhere",
        type: "TOOL_PRACTICE",
        objective: "Generate genuinely different copy variants for two channels from the same brief.",
        whyItMatters: "The same message needs a different shape on social versus email — asking AI for 'copy' without specifying the channel produces one-size-fits-none results.",
        concept: "Email, social, and web copy need different lengths and tones even for the same message.",
        example: "The same offer becomes a 3-line punchy post on social and a warmer, longer email.",
        tryItPrompt: "Generate email and social copy variants from your brief and compare the differences.",
        evaluatePrompt: "AI produces identical copy for both the email and social post, just with the platform name swapped in a header. Does this meet the goal of channel-specific copy?",
        exercise: "For your next campaign, generate at least 2 channel variants and check that they'd actually read differently to someone scrolling past both.",
        knowledgeCheckQuestion: "What should you specify in the prompt to get genuinely different copy per channel?",
        knowledgeCheckOptions: [
          "Nothing — AI adapts automatically",
          "The channel's format, typical length, and tone expectations",
          "Only the word count",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Channel-specific copy requires channel-specific instructions — format and tone need to be in the prompt, not assumed.",
        skills: ["prompting"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Monthly Reporting Narratives",
    title: "Draft financial commentary your board will actually read",
    description: "Turn budget variance data into a clear narrative with AI.",
    department: "Finance",
    role: "Financial Analysts",
    skills: ["evaluation"],
    tools: ["ChatGPT", "QuickBooks"],
    lessons: [
      {
        title: "Why variance data needs a narrative",
        type: "CONCEPT",
        objective: "Explain why raw variance numbers need a written explanation before they reach stakeholders.",
        whyItMatters: "A number without context ('+12% marketing spend') tells a stakeholder almost nothing about whether it's a problem — the narrative is what makes the report useful.",
        concept: "Numbers alone don't tell stakeholders why something changed — AI can draft the 'why' from the data.",
        example: "Instead of just '+12% marketing spend,' a narrative reads: 'Marketing spend rose 12% due to an accelerated Q3 campaign launch.'",
        tryItPrompt: "Feed a budget-to-actual table into AI and ask it to draft variance commentary.",
        evaluatePrompt: "AI's variance narrative states a cause with confident language ('due to') but you haven't actually confirmed that cause with the department yet. Is that language appropriate?",
        exercise: "Feed a budget-to-actual table into AI and ask it to draft variance commentary.",
        knowledgeCheckQuestion: "What makes a variance narrative more useful than the raw numbers alone?",
        knowledgeCheckOptions: [
          "It's shorter",
          "It explains why the number changed, in plain language",
          "It removes numbers a reader might question",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "The value of a narrative is the 'why' — but only state a cause with confidence once it's actually confirmed, not just inferred from the number.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Keeping sensitive data safe when using AI",
        type: "DECISION_EXERCISE",
        objective: "Decide what level of financial detail is safe to share with an AI tool under company policy.",
        whyItMatters: "Financial data is exactly the kind of information that needs to stay inside approved tools — a comfortable habit with a general AI tool can become a real exposure with the wrong data.",
        concept: "Only use AI tools approved under your company's data governance policy for financial data.",
        example: "Aggregate or anonymize figures when testing a new AI tool before it's formally approved.",
        tryItPrompt: "Check which AI tools are approved for financial data at your company before your next report.",
        evaluatePrompt: "A colleague pastes an unreleased department budget with vendor names into a general-purpose AI chatbot to save time drafting commentary. Is this appropriate?",
        exercise: "Before your next report, confirm in writing which AI tool is approved for the specific data you're working with.",
        knowledgeCheckQuestion: "What's the safest approach when you're unsure if a tool is approved for a specific type of financial data?",
        knowledgeCheckOptions: [
          "Use it anyway since it's just for a draft",
          "Aggregate/anonymize the data first, or confirm approval before using real figures",
          "Only avoid it if the data includes customer names",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "When in doubt about a tool's approval status, aggregate the data or check first — 'just a draft' is still real financial data leaving your systems.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Job Descriptions & Resume Screening",
    title: "Hire faster without losing the human review",
    description: "Draft job descriptions and pre-screen resumes with AI.",
    department: "HR",
    role: "Recruiters",
    skills: ["evaluation"],
    tools: ["ChatGPT", "Notion"],
    lessons: [
      {
        title: "Writing a job description in minutes, not hours",
        type: "PROMPT_EXERCISE",
        objective: "Draft a strong first-pass job description from role, level, and must-have skills.",
        whyItMatters: "A blank page is the slowest part of writing a JD — giving AI the 2-3 facts only you know turns that blank page into a first draft in minutes.",
        concept: "AI can draft a strong first version from just the role, level, and key requirements.",
        example: "Input the role title and 3 must-have skills; AI drafts the full JD including responsibilities and qualifications.",
        tryItPrompt: "Draft a JD for an open role using AI, then edit it for your company's voice.",
        evaluatePrompt: "AI's draft JD lists 'must have 10+ years experience' for a role you specified as entry-level. Should you keep this requirement?",
        exercise: "Draft a JD for an open role using AI, then edit it for your company's voice.",
        knowledgeCheckQuestion: "What's the fastest way to get a strong first-draft JD from AI?",
        knowledgeCheckOptions: [
          "Ask for 'a job description' with no other detail",
          "Give AI the role, level, and 2-3 must-have skills",
          "Write the whole thing yourself first, then ask AI to polish it",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "A few real, specific inputs (role, level, must-haves) produce a far more useful draft than a vague one-word request.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Using AI screening without introducing bias",
        type: "DECISION_EXERCISE",
        objective: "Recognize when AI's screening criteria have drifted from the role's actual written requirements.",
        whyItMatters: "AI screening can process resumes far faster than a manual read, but if its criteria drift toward proxies like university name, you inherit a bias problem you'll have to answer for later.",
        concept: "AI screening should score against explicit role criteria — always spot-check for bias before trusting the shortlist.",
        example: "Review a sample of AI-screened-out resumes each month to check the criteria are working as intended.",
        tryItPrompt: "List the explicit criteria you'd want AI to screen for in your next open role.",
        evaluatePrompt: "AI explains a candidate was ranked lower partly because they attended a 'less selective' university. Is this an appropriate screening criterion?",
        exercise: "For your next screening pass, write down your criteria before running any resumes through AI, and spot-check 5 resumes it screened out.",
        knowledgeCheckQuestion: "What should trigger a human override of an AI screening decision?",
        knowledgeCheckOptions: [
          "The candidate has an unusual resume format",
          "AI's stated reasoning references something not on your written job requirements",
          "The candidate applied outside business hours",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Any AI-stated screening reason that isn't one of your written requirements is a signal to override, not a tiebreaker to accept.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Product Requirement Docs",
    title: "Turn interview notes into a PRD your team can act on",
    description: "Draft structured PRDs from scattered notes with AI.",
    department: "Product",
    role: "Product Managers",
    skills: ["prompting", "evaluation"],
    tools: ["Claude", "Notion"],
    lessons: [
      {
        title: "From messy notes to a structured PRD",
        type: "PROMPT_EXERCISE",
        objective: "Turn a set of raw discovery notes into a structured PRD using AI.",
        whyItMatters: "Discovery notes are rarely organized in the shape a PRD needs — AI is well-suited to that restructuring, but only if you feed it real notes, not a summary you've already condensed.",
        concept: "AI can organize scattered interview notes into goals, requirements, and open questions.",
        example: "Feed in 5 pages of raw notes; AI returns a PRD with clear sections.",
        tryItPrompt: "Turn your most recent set of discovery notes into a structured PRD with AI.",
        evaluatePrompt: "AI's draft PRD includes a requirement that doesn't appear anywhere in your original interview notes. Where did it likely come from, and what should you do?",
        exercise: "Turn your most recent set of discovery notes into a structured PRD with AI.",
        knowledgeCheckQuestion: "What should you feed AI to get the most accurate structured PRD?",
        knowledgeCheckOptions: [
          "A one-paragraph summary you wrote of the notes",
          "The raw, unsummarized interview notes",
          "Just the feature name",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Feeding AI your own summary compounds information loss — give it the raw notes and let it do the structuring.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Knowing what to keep human-authored in a PRD",
        type: "REFLECTION",
        objective: "Identify which parts of a PRD should stay in your own words even after AI drafts a structure.",
        whyItMatters: "A PRD's goals and trade-off calls represent your judgment, not just a synthesis of notes — letting AI's phrasing stand in for your own reasoning here creates real ambiguity for the team executing on it.",
        concept: "AI is strong at structuring what's already in your notes; it's not a substitute for your own prioritization judgment on open questions and trade-offs.",
        example: "AI can format 'Goals' and 'Requirements' sections well, but a PM should personally write the 'Open questions' and any explicit trade-off decision.",
        tryItPrompt: "Look at your last AI-drafted PRD and mark which sections reflect your own judgment versus a restatement of notes.",
        evaluatePrompt: "An AI-drafted PRD states a trade-off decision ('we will deprioritize X') that you never actually discussed with the team. Should this stand as written?",
        exercise: "In your next PRD, rewrite the 'Open questions' and any trade-off section in your own words even if AI drafted a version.",
        knowledgeCheckQuestion: "Which part of a PRD is least appropriate to leave entirely as AI wrote it?",
        knowledgeCheckOptions: [
          "The formatting of the requirements list",
          "An explicit trade-off or prioritization decision",
          "The section headers",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Structure and formatting are safe to delegate; the actual prioritization judgment calls are yours to make and state in your own words.",
        skills: ["evaluation"],
        durationMin: 7,
      },
    ],
  },
  {
    workflowTitle: "Demand Forecasting Assistant",
    title: "Improve demand forecasts with AI-assisted signals",
    description: "Incorporate external signals into demand forecasts and know when to trust the model.",
    department: "Operations",
    role: "Operations Planners",
    skills: ["workflowDesign", "evaluation"],
    tools: ["Excel", "OpenAI"],
    lessons: [
      {
        title: "Why AI forecasts need a human sanity check",
        type: "CONCEPT",
        objective: "Explain why an AI-assisted forecast still needs a planner's review before it drives decisions.",
        whyItMatters: "A forecasting model can incorporate more signals than a spreadsheet alone, but it can also confidently extrapolate from a pattern that doesn't hold this time — the sanity check is what catches that.",
        concept: "AI-assisted forecasting incorporates external signals (seasonality, promotions, trends) that a spreadsheet-only forecast would miss, but its output is a starting estimate, not a guarantee.",
        example: "A forecast that assumes last year's holiday pattern repeats may miss a planned promotion or a supply constraint this year that changes the picture entirely.",
        tryItPrompt: "Pull your most recent AI-assisted forecast and identify one assumption behind it you haven't verified this cycle.",
        evaluatePrompt: "An AI-assisted forecast shows a sharp demand spike for one SKU with no explanation given. What would you check before trusting this number?",
        exercise: "Before finalizing your next forecast, list the 2-3 external factors this cycle that the model wouldn't automatically know about.",
        knowledgeCheckQuestion: "What's the main reason an AI-assisted forecast still needs a planner's review?",
        knowledgeCheckOptions: [
          "The AI is usually wrong",
          "It may not account for a factor unique to this cycle that a planner would know about",
          "Forecasts don't need review once AI is involved",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI extrapolates from patterns in data; a planner knows about the exceptions this cycle that aren't in that data yet.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Reading confidence intervals, not just point forecasts",
        type: "DECISION_EXERCISE",
        objective: "Decide how much weight to give a forecast based on its confidence range, not just the headline number.",
        whyItMatters: "Two forecasts can show the same headline number with very different confidence — treating them the same risks over-committing inventory on a shaky estimate.",
        concept: "A forecast's confidence interval tells you how much to trust the point estimate — a wide range means more caution is warranted even if the number itself looks fine.",
        example: "A forecast of 1,000 units with a range of 800-1,200 deserves more caution in ordering than one with a range of 950-1,050.",
        tryItPrompt: "Find a recent forecast's confidence range and describe what it implies about how you should plan around it.",
        evaluatePrompt: "A planner orders inventory based solely on the point forecast, ignoring that the confidence range spans nearly double the low estimate. What's the risk here?",
        exercise: "For your next order decision, explicitly note the forecast's confidence range alongside the point number before committing.",
        knowledgeCheckQuestion: "A wide confidence interval on a forecast means:",
        knowledgeCheckOptions: [
          "The forecast is definitely wrong",
          "There's more uncertainty, and more caution is warranted in planning around it",
          "It can be ignored since the point estimate is what matters",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "The point forecast is only half the picture — the confidence range tells you how much to bet on it.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
  {
    workflowTitle: "Contract Review Assistant",
    title: "Speed up contract review without skipping legal judgment",
    description: "Use AI for a first-pass playbook comparison while keeping real risk decisions with an attorney.",
    department: "Legal",
    role: "Contracts Counsel",
    skills: ["evaluation"],
    tools: ["OpenAI"],
    lessons: [
      {
        title: "What AI can flag vs. what only an attorney can decide",
        type: "CONCEPT",
        objective: "Draw a clear line between clause-comparison (AI can do this) and risk acceptance (only an attorney should).",
        whyItMatters: "The efficiency gain from AI contract review only holds up if the division of labor is right — AI finding deviations fast is a real win; AI deciding whether a deviation is acceptable is a real risk.",
        concept: "AI can compare contract language against a standard playbook and flag deviations quickly and consistently. Whether a flagged deviation is acceptable risk is a judgment call for a licensed attorney.",
        example: "AI flagging 'the liability cap was changed from mutual to one-sided' is useful. AI recommending 'accept this change, it's reasonable' oversteps into legal judgment.",
        tryItPrompt: "Think of the last contract you reviewed — which parts were mechanical comparison, and which required your own judgment call?",
        evaluatePrompt: "AI's contract review output both flags a changed clause and recommends accepting it. Which part of that output would you keep, and which would you discard?",
        exercise: "On your next contract review, use AI only to build the list of what changed — write your own acceptance recommendation separately.",
        knowledgeCheckQuestion: "What is AI well-suited to do in contract review?",
        knowledgeCheckOptions: [
          "Deciding whether a liability cap is acceptable for this deal",
          "Comparing clause language against a standard playbook to flag deviations",
          "Signing off on the final redline",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Let AI build the list of what changed; keep the judgment about whether a change is acceptable with a licensed attorney.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Comparing a redline against your standard playbook",
        type: "TOOL_PRACTICE",
        objective: "Use AI to produce a clause-by-clause comparison of a redlined contract against your standard terms.",
        whyItMatters: "A thorough manual comparison of a long redlined contract is slow and easy to skim past a subtle change — a structured AI-assisted comparison catches what a tired read might miss.",
        concept: "AI flags non-standard or high-risk clauses against the company's playbook before legal review.",
        example: "AI identifies that Section 8's liability cap changed from mutual to vendor-only, and Section 12's data handling terms were broadened.",
        tryItPrompt: "Feed AI your standard terms and a redlined contract, and ask it to list every clause that deviates.",
        evaluatePrompt: "AI's comparison lists 5 flagged clauses. On manual review, you find a 6th change AI didn't catch, in a footnote. What does this tell you about relying on AI comparison alone?",
        exercise: "On your next contract, run the AI comparison first, then do one manual pass focused specifically on footnotes and appendices.",
        knowledgeCheckQuestion: "Why should an AI-assisted clause comparison still be followed by a targeted manual pass?",
        knowledgeCheckOptions: [
          "AI comparisons are never useful",
          "AI may miss changes in unusual locations like footnotes or appendices",
          "It's required by the tool's license",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI comparison is a strong first pass, not a guaranteed complete one — a short targeted manual check covers its blind spots.",
        skills: ["evaluation"],
        durationMin: 9,
      },
    ],
  },
  {
    workflowTitle: "AI-Assisted Board Reporting",
    title: "Turn department updates into a board-ready narrative",
    description: "Synthesize scattered updates into an accurate board memo with AI.",
    department: "Executive",
    role: "Executives",
    skills: ["evaluation", "automation"],
    tools: ["Claude", "Notion"],
    lessons: [
      {
        title: "Synthesizing scattered updates without losing accuracy",
        type: "PROMPT_EXERCISE",
        objective: "Turn several inconsistent team updates into one coherent draft narrative using AI.",
        whyItMatters: "Reconciling five different team leads' updates manually eats the time you need to actually verify the numbers — AI can do the reconciliation so you can spend your time checking, not assembling.",
        concept: "AI drafts a first-pass board narrative from department metrics; executives edit and finalize.",
        example: "Five Slack updates and a rough spreadsheet become one structured one-page summary organized by department.",
        tryItPrompt: "Feed AI your team's raw updates (not your own summary of them) and ask for a one-page synthesis organized by department.",
        evaluatePrompt: "AI's synthesized narrative states 'CSAT rose 12% quarter-over-quarter' by comparing two updates that actually covered different time periods. What's the risk in this figure?",
        exercise: "For your next board update, feed AI the raw source updates and compare its draft against each source line by line.",
        knowledgeCheckQuestion: "What's the best raw material to give AI when synthesizing multiple team updates?",
        knowledgeCheckOptions: [
          "Your own condensed summary of the updates",
          "The original, unsummarized updates from each team",
          "Just the numbers, with no context",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "Synthesizing from the original sources preserves the detail needed to catch a mismatch — synthesizing from your own summary compounds whatever you already left out.",
        skills: ["prompting"],
        durationMin: 8,
      },
      {
        title: "Verifying every number before it reaches the board",
        type: "DECISION_EXERCISE",
        objective: "Decide which figures in an AI-drafted board memo need verification before the memo is final.",
        whyItMatters: "A board memo is read and acted on by people who won't check your math — an unverified figure that turns out wrong costs credibility in a way few other documents do.",
        concept: "Any figure that will appear in a board-facing document must be verified against its source system before the memo is finalized.",
        example: "An 'estimated 400 hours saved' figure that doesn't trace back to any specific source number shouldn't go into the memo unchanged.",
        tryItPrompt: "Take an AI-drafted memo and trace every number back to a specific source line before treating it as final.",
        evaluatePrompt: "The memo is due in 10 minutes and one figure's source is ambiguous. Do you include it as-is, remove it, or flag it as an estimate?",
        exercise: "Before your next board memo goes out, personally trace each figure back to its source and note anywhere you couldn't.",
        knowledgeCheckQuestion: "What should you do with a figure in a board memo whose source you can't verify in time?",
        knowledgeCheckOptions: [
          "Include it as stated since it sounds reasonable",
          "Remove it or clearly label it as an estimate rather than a confirmed figure",
          "Round it to a cleaner number",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "An honestly-labeled estimate is far better than a confident-sounding number you can't actually trace back to its source.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
  {
    workflowTitle: "AI Code Review Assistant",
    title: "Use AI code review without skipping design thinking",
    description: "Get a fast AI first-pass review while keeping human review focused on what actually needs it.",
    department: "Engineering",
    role: "Software Engineers",
    skills: ["automation", "evaluation"],
    tools: ["OpenAI", "Jira"],
    lessons: [
      {
        title: "What AI catches well in a diff, and what it misses",
        type: "CONCEPT",
        objective: "Distinguish between review tasks AI handles well (style, common bugs, missing tests) and ones it doesn't (architecture, intent).",
        whyItMatters: "Knowing AI's real strengths and blind spots in code review lets you actually save reviewer time instead of just adding an extra pass that catches the same things a human would.",
        concept: "AI reviews the diff first for bugs, style, and missing tests, then a human reviewer focuses on design.",
        example: "AI reliably catches an unhandled null case or a missing test for a new branch; it's much weaker at judging whether the overall approach is the right one for the codebase's direction.",
        tryItPrompt: "Look at your last AI-reviewed PR and separate its comments into 'mechanical' (style, bugs, tests) versus 'design' (architecture, approach).",
        evaluatePrompt: "AI's review comment says 'this function could be refactored for better architecture' with no further detail. Is this the kind of feedback AI is well-suited to give?",
        exercise: "On your next PR, ask AI to review first, then spend your own review time only on the design-level questions it can't meaningfully answer.",
        knowledgeCheckQuestion: "Which task is AI generally weaker at in code review?",
        knowledgeCheckOptions: [
          "Flagging an unhandled null case",
          "Judging whether the overall architectural approach fits the codebase's direction",
          "Noticing a missing test for a new code path",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "AI is strong on the mechanical review; a human reviewer's time is best spent on the design judgment AI can't make.",
        skills: ["fundamentals"],
        durationMin: 8,
      },
      {
        title: "Focusing human review on design, not syntax",
        type: "DECISION_EXERCISE",
        objective: "Decide when to defer to AI's mechanical review versus when a PR needs deeper human design review.",
        whyItMatters: "If human reviewers keep re-checking what AI already covered, the workflow adds time instead of saving it — the discipline is trusting AI's mechanical pass and moving straight to design questions.",
        concept: "A human reviewer focuses on architecture and design decisions once AI has covered the mechanical pass.",
        example: "If AI's review found no bugs or style issues, a human reviewer can skip re-checking syntax and go straight to 'does this approach make sense here?'",
        tryItPrompt: "For your next review, decide upfront which specific design question you'll focus on, assuming AI has the mechanical pass covered.",
        evaluatePrompt: "A reviewer spends 20 minutes re-checking style issues that AI's review already flagged and the author already fixed. Was this a good use of review time?",
        exercise: "Track your next 5 PR reviews: note how much time went to mechanical re-checking versus genuine design discussion.",
        knowledgeCheckQuestion: "What's the sign that the AI-plus-human review workflow is working well?",
        knowledgeCheckOptions: [
          "The human reviewer re-checks everything AI already covered",
          "The human reviewer spends their time on design questions AI didn't address",
          "PRs take longer to merge than before",
        ],
        knowledgeCheckCorrectIndex: 1,
        takeaway: "The workflow pays off when human review time shifts entirely to design judgment, not when it duplicates AI's mechanical pass.",
        skills: ["evaluation"],
        durationMin: 8,
      },
    ],
  },
];
